site_name: Dokumentasi Perencanaan Dinas Perhubungan Kabupaten Pasuruan
theme:
  name: material
  logo: assets/dishub.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: id
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo 
      accent: blue
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: blue


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ibrahimaji
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibrahimcious

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

copyright: |
  &copy; 2023 <a href="https://github.com/ibrahimaji"  target="_blank" rel="noopener">Sub Bagian Penyusunan Program dan Pelaporan Dinas Perhubungan Kabupaten Pasuruan</a>
